### ISSUE TITLE
Prune only works with Play 2.4.x

### ISSUE THREAD

**Issue by toddwest** [playframework/prune#1]
Prune attempts to automatically detect the version of play that it's testing against by reading this file:

https://github.com/playframework/playframework/blob/2.4.x/framework/version.sbt

However this file doesn't exist in any of the other branches (2.1.x, 2.2.x, 2.3.x) so when you attempt to run against them you get the following exception:

```
Exception in thread "main" java.nio.file.NoSuchFileException: /Users/home/.prune/play/framework/version.sbt
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
    at java.nio.file.Files.newByteChannel(Files.java:361)
    at java.nio.file.Files.newByteChannel(Files.java:407)
    at java.nio.file.Files.readAllBytes(Files.java:3152)
    at com.typesafe.play.prune.PlayVersion$.readPlayVersionFromFile(PlayVersion.scala:16)
    at com.typesafe.play.prune.BuildApp$.buildAppDirectly(BuildApp.scala:139)
    at com.typesafe.play.prune.BuildApp$.com$typesafe$play$prune$BuildApp$$newAppBuild$1(BuildApp.scala:42)
    at com.typesafe.play.prune.BuildApp$$anonfun$buildApp$2.com$typesafe$play$prune$BuildApp$$anonfun$$buildUnlessTooManyFailures$1(BuildApp.scala:94)
    at com.typesafe.play.prune.BuildApp$$anonfun$buildApp$2$$anonfun$apply$5.apply(BuildApp.scala:104)
    at com.typesafe.play.prune.BuildApp$$anonfun$buildApp$2$$anonfun$apply$5.apply(BuildApp.scala:102)
    at scala.Option.fold(Option.scala:157)
    at com.typesafe.play.prune.BuildApp$$anonfun$buildApp$2.apply(BuildApp.scala:105)
    at com.typesafe.play.prune.BuildApp$$anonfun$buildApp$2.apply(BuildApp.scala:85)
    at scala.Option.fold(Option.scala:157)
    at com.typesafe.play.prune.BuildApp$.buildApp(BuildApp.scala:85)
    at com.typesafe.play.prune.RunTest$.runTestTask(RunTest.scala:42)
    at com.typesafe.play.prune.Prune$.loop$1(Prune.scala:243)
    at com.typesafe.play.prune.Prune$.test(Prune.scala:248)
    at com.typesafe.play.prune.Prune$.main(Prune.scala:101)
    at com.typesafe.play.prune.Prune.main(Prune.scala)
```

and the test execution doesn't continue any further. It seems as if a backup mechanism is needed to correctly identify the play version when the version.sbt file is not available?

**Comment by ktoso** [comment]
The good news is that prune nowadays works with 2.6 though which is more relevant I think :-)

**Comment by gmethvin** [comment]
I'll close since we don't support pre-2.4.x and prune does work with newer versions.
